### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by silvadaniel88** [NEEDS-LS/CARapp#1]
When I try to install the package I get the following error:

"
Installing package into ‘C:/Users/danie/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'restauraRapp' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file 'CMA.RData' has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  número mágico do arquivo de restauração inválido (arquivo pode estar corrompido) -- nenhum dado carregado
ERROR: lazydata failed for package 'restauraRapp'
* removing 'C:/Users/danie/AppData/Local/R/win-library/4.2/restauraRapp'
"
All necessary packages are up to date, and I am using the newest R and RStudio versions.

**Comment by JCLAraujo** [comment]
A different version of the database had to be created after replacing the Buri/SP database with the Campina do Monte Alegre/SP database to ensure compatibility with various systems and versions of the packages associated with the functionality of the functions. The issue was resolved by replacing the existing database with one using the correct version.
